// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js+dts"
// @generated from file tournament_service.proto (package chesslive, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTournamentRequest, CreateTournamentResponse } from "./tournament_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chesslive.TournamentService
 */
export declare const TournamentService: {
  readonly typeName: "chesslive.TournamentService",
  readonly methods: {
    /**
     * Crear torneo
     *
     * @generated from rpc chesslive.TournamentService.CreateTournament
     */
    readonly createTournament: {
      readonly name: "CreateTournament",
      readonly I: typeof CreateTournamentRequest,
      readonly O: typeof CreateTournamentResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

