// @generated by protoc-gen-es v1.10.1 with parameter "target=js+dts"
// @generated from file tournament_service.proto (package chesslive, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Crear torneo
 *
 * @generated from message chesslive.CreateTournamentRequest
 */
export const CreateTournamentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "chesslive.CreateTournamentRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "start_date", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message chesslive.CreateTournamentResponse
 */
export const CreateTournamentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "chesslive.CreateTournamentResponse",
  () => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

