// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js+dts"
// @generated from file tournament_service.proto (package chesslive, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTournamentRequest, CreateTournamentResponse } from "./tournament_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chesslive.TournamentService
 */
export const TournamentService = {
  typeName: "chesslive.TournamentService",
  methods: {
    /**
     * Crear torneo
     *
     * @generated from rpc chesslive.TournamentService.CreateTournament
     */
    createTournament: {
      name: "CreateTournament",
      I: CreateTournamentRequest,
      O: CreateTournamentResponse,
      kind: MethodKind.Unary,
    },
  }
};

