// @generated by protoc-gen-es v1.10.1 with parameter "target=js+dts"
// @generated from file tournament_service.proto (package chesslive, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Crear torneo
 *
 * @generated from message chesslive.CreateTournamentRequest
 */
export declare class CreateTournamentRequest extends Message<CreateTournamentRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * @generated from field: string start_date = 4;
   */
  startDate: string;

  constructor(data?: PartialMessage<CreateTournamentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "chesslive.CreateTournamentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateTournamentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateTournamentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateTournamentRequest;

  static equals(a: CreateTournamentRequest | PlainMessage<CreateTournamentRequest> | undefined, b: CreateTournamentRequest | PlainMessage<CreateTournamentRequest> | undefined): boolean;
}

/**
 * @generated from message chesslive.CreateTournamentResponse
 */
export declare class CreateTournamentResponse extends Message<CreateTournamentResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  constructor(data?: PartialMessage<CreateTournamentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "chesslive.CreateTournamentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateTournamentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateTournamentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateTournamentResponse;

  static equals(a: CreateTournamentResponse | PlainMessage<CreateTournamentResponse> | undefined, b: CreateTournamentResponse | PlainMessage<CreateTournamentResponse> | undefined): boolean;
}

